create or replace
PACKAGE P_SECURITY AS
TYPE cur_EmpInfo IS REF CURSOR;

FUNCTION F_SECURITY(
P_SECID IN TBL_SECURITY.SEC_ID%TYPE,
P_SECPASSWORD IN TBL_SECURITY.SEC_PASSWORD%TYPE)
RETURN NUMBER;

PROCEDURE P_EMP_INFO (
P_EMPLOYEEID IN EMPLOYEES.EMPLOYEE_ID%TYPE, 
p_info OUT cur_EmpInfo);

END P_SECURITY;